#!/bin/bash
# GRAP Quality Validation Suite Runner
# Executes all validation tests and generates summary report

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
REPORT_FILE="validation_report_${TIMESTAMP}.md"

cd "$PROJECT_ROOT"

echo "=== GRAP Quality Validation Suite ==="
echo "Timestamp: $(date)"
echo "Project root: $PROJECT_ROOT"
echo "Report file: $REPORT_FILE"
echo

# Check prerequisites
echo "Checking prerequisites..."
if [[ ! -d "cl407" ]]; then
    echo "❌ ERROR: cl407/ directory not found"
    exit 1
fi

if [[ ! -f "grax_output/grap_output.json" ]]; then
    echo "❌ ERROR: grax_output/grap_output.json not found"
    echo "   Please run GRAP analysis first"
    exit 1
fi

echo "✅ Prerequisites check passed"
echo

# Run validation tests
echo "=== Running Node State Reliability Analysis ==="
python3 tests/validation/analyze_node_state_reliability.py | tee "${REPORT_FILE}.reliability"

echo
echo "=== Running Detailed Pattern Analysis ==="
python3 tests/validation/analyze_pattern_details.py | tee "${REPORT_FILE}.patterns"

echo
echo "=== Running UUID Consistency Validation ==="
python3 tests/validation/analyze_uuid_consistency.py | tee "${REPORT_FILE}.uuid"

echo
echo "=== Running Entity Coverage Analysis ==="
python3 tests/validation/analyze_entity_coverage.py | tee "${REPORT_FILE}.coverage"

# Generate summary report
echo
echo "=== Generating Summary Report ==="

cat > "$REPORT_FILE" << EOF
# GRAP Validation Report - $(date)

## Test Execution Summary

**Validation Suite Version**: 1.0  
**Execution Time**: $(date)  
**Project Root**: $PROJECT_ROOT  

## Test Results

### Node State Reliability Analysis
\`\`\`
$(cat "${REPORT_FILE}.reliability")
\`\`\`

### Pattern Analysis Details  
\`\`\`
$(cat "${REPORT_FILE}.patterns")
\`\`\`

### UUID Consistency Validation
\`\`\`
$(cat "${REPORT_FILE}.uuid")
\`\`\`

### Entity Coverage Analysis
\`\`\`
$(cat "${REPORT_FILE}.coverage")
\`\`\`

## Quick Assessment

EOF

# Extract key metrics for quick assessment
TOTAL_RAW=$(grep "Found.*raw shifting events" "${REPORT_FILE}.reliability" | awk '{print $2}')
TOTAL_GRAP=$(grep "Found.*GRAP node_state entities" "${REPORT_FILE}.reliability" | awk '{print $2}')
MATCHING_COMBINATIONS=$(grep "Matching timestamp/node combinations:" "${REPORT_FILE}.reliability" | awk '{print $4}')

if [[ -n "$TOTAL_RAW" && -n "$TOTAL_GRAP" && -n "$MATCHING_COMBINATIONS" ]]; then
    RATIO=$(echo "scale=2; $TOTAL_GRAP / $TOTAL_RAW" | bc 2>/dev/null || echo "N/A")
    
    cat >> "$REPORT_FILE" << EOF
### Key Metrics
- **Raw shifting events detected**: $TOTAL_RAW
- **GRAP node_state entities extracted**: $TOTAL_GRAP
- **Entity extraction ratio**: ${RATIO}x
- **Matching timestamp/node combinations**: $MATCHING_COMBINATIONS

### Assessment
EOF

    if (( $(echo "$RATIO >= 1.5" | bc -l 2>/dev/null || echo "0") )); then
        echo "✅ **PASSED**: Extraction ratio within expected range (${RATIO}x)" >> "$REPORT_FILE"
    else
        echo "⚠️ **WARNING**: Unexpected extraction ratio (${RATIO}x)" >> "$REPORT_FILE"
    fi
    
    if [[ "$MATCHING_COMBINATIONS" -gt 30 ]]; then
        echo "✅ **PASSED**: Good timestamp/node combination matching ($MATCHING_COMBINATIONS)" >> "$REPORT_FILE"
    else
        echo "❌ **FAILED**: Low timestamp/node combination matching ($MATCHING_COMBINATIONS)" >> "$REPORT_FILE"
    fi
else
    echo "⚠️ **WARNING**: Could not extract key metrics from test output" >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" << EOF

## Files Generated
- \`${REPORT_FILE}.reliability\` - Raw reliability test output
- \`${REPORT_FILE}.patterns\` - Raw pattern analysis output  
- \`$REPORT_FILE\` - This summary report

## Next Steps
1. Review detailed analysis in \`tests/validation/NODE_STATE_RELIABILITY_REPORT.md\`
2. Address any failed tests or warnings
3. Archive this report for regression testing comparison

*Generated by GRAP Quality Validation Suite v1.0*
EOF

# Cleanup temporary files
rm -f "${REPORT_FILE}.reliability" "${REPORT_FILE}.patterns" "${REPORT_FILE}.uuid" "${REPORT_FILE}.coverage"

echo "✅ Validation suite completed successfully"
echo "📄 Summary report: $REPORT_FILE"
echo
echo "=== Quick Results ==="
if [[ -n "$TOTAL_RAW" && -n "$TOTAL_GRAP" ]]; then
    echo "Raw events: $TOTAL_RAW | GRAP entities: $TOTAL_GRAP | Ratio: ${RATIO}x"
else
    echo "Check $REPORT_FILE for detailed results"
fi